### ISSUE TITLE
[Refactor] Dark mode may not be needed

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#142]
Right now the crx has a dark mode for graph display. Actually the graph element will use the page theme as default background but not always light mode.

While I am using dark mode in GitHub, the graph will be like below:
![image](https://user-images.githubusercontent.com/8512426/120655428-4030d980-c4b5-11eb-8b35-41ea910b35ed.png)

This is a dark mode already and if I turn on the dark mode, it will be like this:
![image](https://user-images.githubusercontent.com/8512426/120655528-59398a80-c4b5-11eb-8bc6-8f0516ca3913.png)

The background color will be deep blue and not cover all graph background. So maybe we do not need dark at all. WDYT?

**Comment by heming6666** [comment]
**I agree with you. We can remove dark mode in the first version. **

But this feature can be added in the future since some users may want to use `dark`( or `light`) mode even when the page theme is `light` (or `dark`).

Current implementation are:
- Read the page theme: `light` or `dark`
- Pass the theme to graph component

As what you said, the problems are:
- The background color is deep blue when in dark mode
- [`Antv` doesn't support switching the theme](https://graphin.antv.vision/en-US/graphin/render/theme/)

The solutions are:
- Customized the background color when in dark mode
- Wait until `Antv` supports switching the theme
