### ISSUE TITLE
[Bug] Hypercrx on private repository

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#276]
## Introduction to the issue

Hi, recently I have been working on a private repository and I find that hypercrx hasn't handled situations on a private repository. No graph is displayed under the `Perceptor` tab and there is a display error on the second and third graph.

## screenshot
![image](https://user-images.githubusercontent.com/39271899/154806861-4c4a668e-f48f-4615-9987-833e170e256f.png)
![image](https://user-images.githubusercontent.com/39271899/154806866-ef0ee9f7-c603-4583-84b9-d6629b92ff45.png)

**Comment by tyn1998** [comment]
Thank you for your report. Private repos should not be injected with perceptor tab, we will handle this.

**Comment by wxharry** [comment]
I found that `hypertrons-crx` does have error handling on private repositories, or to be more accurate, on no-data situations, sorry for issuing a bug for that. I mistakenly thought it is an unhandled error page because it looks like one, and I immediately realized that I am wrong after I take a look at the source code. Sorry again.

**Comment by tyn1998** [comment]
Hi wxharry, you are not wrong. I think the problem you pointed out still exists, because we(X-lab) only care about public data so private repos do nothing with Perceptor. The "no-data situation" is designed for public repos that are not active enough to be analyzed due to a cost consideration.

Any issue is welcomed and appreciated, and please feel free to fire an issue!

**Comment by tyn1998** [comment]
closed by #320, Thank you @wxharry !
