### ISSUE TITLE
[CI/CD] Update project version

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#333]
## Type of Issue

- [x] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue

In [my previous commit](db21e5e5aaff33a55c84bced9894e6e8619431a1), we updated the version in `package.json` manually. This could be a problem when contributors are working together. Since `hypercrx` are going to embrace more contributors, it needs to be fixed as soon as possible.

## Possible Fix
1. Command `npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]` can help updating a version.

**Comment by tyn1998** [comment]
Totally agree! We need another strategy to handle version updating.

**Comment by tyn1998** [comment]
Maybe pre means preview? Just refer to releases of [Qv2ray](https://github.com/Qv2ray/Qv2ray/releases?page=1).
<img width="937" alt="image" src="https://user-images.githubusercontent.com/32434520/163513559-f11594ea-abe2-476a-bd65-49591fbd1e29.png">

**Comment by tyn1998** [comment]
We should have "release" for those will be pushed to chrome/edge store.

**Comment by wxharry** [comment]
Here is what I understand on version updating, please feel free to correct me!
1. The contributors are not responsible for modifying the version number. 
2. Version number is a tag given by someone responsible for the project.
3. Any other changes relevant to the Version number is done by CI/CD. 
4. Release and publish is done by CI/CD. 
5. Since we are using numbers not `latest` to label the releases, there will be history of releases.

**Comment by tyn1998** [comment]
Hey Harray! Sorry to tell you that I, in practice, do not have a clear picture about the version management things. But I can give you some facts and what flow hypercrx might need.

Facts:
- 3 files are related to version numbers
  - package.json (the number in this file will also be written into manifest.json by one of the webpack plugins)
  - publish/update_information.json (the file will be read in CI/CD and then pushed to oss for version checking on user end)
  - src/mock/background.data.ts (this is mock version of update_infomation.json, only used in development)
- currently I modify the version number after fixing a bug or adding a feature, MANUALLY, which is a bad way

Needs:
- "release" should means the packages will be published on Chrome/Edge stores
- PRs that fix a typo should not trigger a workflow that produce a "release" packages
  - but they still produce packages
- it is the maintainer(s) that manually trigger the "release" workflow

Notes:
Since the version numbers are in .json .ts files, so we may figure a way out to allow CI/CD workflow to change these numbers easily. e.g. a higher level constant value which will be imported in files?

**Comment by tyn1998** [comment]
> Hey Harray! Sorry to tell you that I, in practice, do not have a clear picture about the version management things. But I can give you some facts and what flow hypercrx might need.
> 
> Facts:
> 
> * 3 files are related to version numbers
>   
>   * package.json (the number in this file will also be written into manifest.json by one of the webpack plugins)
>   * publish/update_information.json (the file will be read in CI/CD and then pushed to oss for version checking on user end)
>   * src/mock/background.data.ts (this is mock version of update_infomation.json, only used in development)
> * currently I modify the version number after fixing a bug or adding a feature, MANUALLY, which is a bad way
> 
> Needs:
> 
> * "release" should means the packages will be published on Chrome/Edge stores
> * PRs that fix a typo should not trigger a workflow that produce a "release" packages
>   
>   * but they still produce packages
> * it is the maintainer(s) that manually trigger the "release" workflow
> 
> Notes: Since the version numbers are in .json .ts files, so we may figure a way out to allow CI/CD workflow to change these numbers easily. e.g. a higher level constant value which will be imported in files?

We'd better learn from other well organized projects :)

**Comment by tyn1998** [comment]
We'd better learn from other well organized projects :)

**Comment by wxharry** [comment]
Thank you for your reply! It is really important to figure out what hypercrx needs before getting started and now I am having a basic picture. As for those numbers, maybe we can use js scripts to update and it can be triggered in CI/CD. I am also a beginner on this and is looking for other projects for a practical way to do this. Any examples and ideas are welcome!

**Comment by tyn1998** [comment]
Keep discussing~

**Comment by wxharry** [comment]
We can add scripts to the project to handle the release and deployment work. Inspired by [how prettier handle releases](https://github.com/prettier/prettier/tree/main/scripts/release). And scripts on https://github.com/hypertrons/hypertrons-crx/issues/290 can also be added to it.

**Comment by tyn1998** [comment]
Thanks for the info, I will look into it!
