### ISSUE TITLE
[Doc] Draw an illustration to depict our CI/CD workflows and put it to repo wiki

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#368]
### Description

As the title describes

**Comment by wxharry** [comment]
Please check it out! [wiki/CI--CD](https://github.com/hypertrons/hypertrons-crx/wiki/CI--CD)
It has to be CI--CD, not CI/CD because slash is not a valid character in filename.
Also, I used mermaid to draw the diagrams. [mermaid](https://github.com/mermaid-js/mermaid) is an amazing diagramming and charting tool which can render markdown text to diagrams.

**Comment by wxharry** [comment]
I am gonna close this issue since the wiki page has been created
