### ISSUE TITLE
[Feature Enhancement] Allow users to customize days' data for two networks 

### ISSUE THREAD

**Issue by AliceCodeZhang** [hypertrons/hypertrons-crx#403]
### Description

Currently, only supports hardcode 180 days settings for Project Correlation Network and Active Developer Collabration Network on perceptor page.    It would be better to allow users to customize the numbers they want.

**Comment by tyn1998** [comment]
> Hello, @frank-zsy, maybe OpenDigger can consider re-implementing correlation network data and replace the data Hypercrx now uses.

This [feature request](https://github.com/X-lab2017/open-digger/issues/1081) is resolved by https://github.com/X-lab2017/open-digger/pull/1103

Now the period is 90 days because OpenDigger only exports it so. Network data generation is resource consuming. This issue can be reopened if OpenDigger starts to support multi-periods data :)
