### ISSUE TITLE
[Bug] `yarn run build` and `yarn run start` not working on Windows Machine

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#422]
### Description

In the commit [fix: exsiting way to write process.env.XXX does not work](https://github.com/hypertrons/hypertrons-crx/pull/384/commits/791c261fc46b2be03dfd1868c498dfbb9a172fb6), we changed the way to specify environment variables. However, the wary of adding the env variables directly to `yarn run build` and `yarn run start` doesn't work for windows Machine. Catch error:
![image](https://user-images.githubusercontent.com/39271899/180660820-65ef0521-85ae-44ac-8f62-9d176620e451.png) 
becuase we are using windows cmd and the commands are different.

How do we solve this?

**Comment by tyn1998** [comment]
Hi, @wxharry, it was a mistake. Thank you for reporting it!

Before https://github.com/hypertrons/hypertrons-crx/pull/274:

https://github.com/hypertrons/hypertrons-crx/blob/b6dc905133c58ac664b4a6183c6a9c3dec6f6bbb/package.json#L7-L14

After https://github.com/hypertrons/hypertrons-crx/pull/274, all things that related to `cross-env` are removed because they are not needed anymore until https://github.com/hypertrons/hypertrons-crx/pull/384 comes out. But apparently I ignored the different shell syntax between windows cmd/powershell and unix-like bash/zsh/fish then.

We should use [cross-env](https://www.npmjs.com/package/cross-env) again.

**Comment by tyn1998** [comment]
What shell did you use?

**Comment by wxharry** [comment]
windows cmd

**Comment by tyn1998** [comment]
Now I know more about `git bash`, "bash" is more important.
