### ISSUE TITLE
[Feature] 能否在个人首页上把Starred的项目列出来

### ISSUE THREAD

**Issue by a15355447898a** [hypertrons/hypertrons-crx#435]
### Description

就是把标星的项目列出,我不清楚能否实现,加油!

**Comment by tyn1998** [comment]
Hi, @a15355447898a, did you mean show all projects you starred on you profile page, like this?

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/32434520/183012884-c5f68a4e-1abd-4e99-ab3a-581a9150194f.png">

If so, I'm afraid that we won't adopt this idea since it is not so relevant to Hypercrx's purpose :)

**Comment by tyn1998** [comment]
You can refer to [Refined GitHub](https://github.com/refined-github/refined-github), which is an amazing extension that improve your GitHub experience.

**Comment by a15355447898a** [comment]
thanks
