### ISSUE TITLE
[Feature] Background request should be added

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#5]
Now we need to request data from backend to render on crx.

The request module should be added into the common background script which in `common/background/util.js` to provide data request function to the crx.

**Comment by LiuChangFreeman** [comment]
Chrome will forbid extensions to send web requests otherwise they are in the whitelist defined in  `src/manifest.json`
Also, when hacking with the `content-script`, there may be some CROS problems we should handle first. These all lead to the question that we should know where the `back-end` service will be deployed first when developing the extension.
```json
{
  ...
  "permissions": [
    "*://your-domain.com/*",
    ...
  ],
...
}
```

**Comment by heming6666** [comment]
It's out-of-date.

Closed.
