### ISSUE TITLE
[Improvement]  Graph-description of Developer Network collapses

### ISSUE THREAD

**Issue by stealth-bombeer** [hypertrons/hypertrons-crx#647]
### Description

Currently the graph and the description of the Developer Collaboration Network in the User-Profile collpases when they reach a breakpoint thus causing readability-issues,same issue persists for Most Participated Repos 

https://user-images.githubusercontent.com/96366867/231411583-7bbf949f-be03-4f16-8e19-036d96e13ed7.mp4

I can fix up the broken stuffs ,need a thumb's up to go ahead

**Comment by tyn1998** [comment]
Hi @stealth-bombeer thank you for filing this issue!

Actually I think it's not a really big issue since I assume no user would resize the browser window like you did in the screencast 😆 But you can have a try and I'm looking forward to a refined version!

Please comment `/self-assign` then you can go ahead :)

**Comment by stealth-bombeer** [comment]
sorry @tyn1998 to bother you it's starts to stretch even if we work on a split screen and keeps collapsing until the end 

https://user-images.githubusercontent.com/96366867/231448834-584bd862-0d41-4e4c-a682-a8078896c01f.mp4

**Comment by tyn1998** [comment]
Yeah it's far from perfect. If you would like to make it better, just go 🚀
