### ISSUE TITLE
[Bug] Aesthetics and stability improvements

### ISSUE THREAD

**Issue by HalloMelon** [hypertrons/hypertrons-crx#749]
### Version

1.9.1

### Current Behavior

First of all, it is whether it can be further beautified during the display process. Only in a single month, it is also presented in the form of a line chart (if there is only one day, the line chart is drawn by the hour; if there are multiple days, the line chart is drawn by date)：
![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/b202b8dc-5105-4e87-9755-3a1915c328e7)

Secondly, for the same warehouse, there is a situation of unstable triggering, as shown below：
![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/fa43b78f-b21b-4f8d-817e-1b3b3f5ee4a2)
![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/d54942ec-5ee6-4fdb-be3f-be14a218b069)

### Expected Behavior

be more beautiful and stable~

### Environment

```markdown
- OS:Windows 10.0
- Browser:Chrome 117.0.0.0
```

**Comment by Zzzzzhuzhiwei** [comment]
I also met the same problem. 
 
![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/ad0c6b36-5787-461c-a738-b0ec9d1c7ec7)

**Comment by tyn1998** [comment]
Thanks for reporting the issue!

> First of all, it is whether it can be further beautified during the display process.

I belive the chart can be fine tuned for better appearance when there are only one or two bars in the chart.

> Secondly, for the same warehouse, there is a situation of unstable triggering,

Could you give the steps to reproduce the issue? @zhaosj975

BTW, we call it "repository" instead of "warehouse" 😆

**Comment by zhaosj975** [comment]
😯 Sorry for the wrong translation，I will notice this point. And now I see，it is normal.
![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/16c88073-bf99-48d5-b6bc-732ce5073abe)

**Comment by wxharry** [comment]
@Zzzzzhuzhiwei Please provide us with steps to replicate this dupliate labels. Thx~

**Comment by Zzzzzhuzhiwei** [comment]
As the GIF shows:

![截图](https://github.com/hypertrons/hypertrons-crx/assets/115639837/ef730b3c-2391-43e2-b57d-c8b55790ea41)

**Comment by zhaosj975** [comment]
![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/871956ca-276f-4601-b910-4fba56bc9b0f)

And the lables even don't be shown in this repo.

**Comment by wxharry** [comment]
> As the GIF shows:

Please point out the key steps to replicate this bug, I had to watch the gif for 20+ times to understand what did you do. My guess is that if we click on another tab very quickly when it is loading the repo code page, there will be duplicate labels. Correct me if I am wrong.

**Comment by wxharry** [comment]
Hey Scarlett, thanks for your suggestion on the charts. A small advice on creating an issue: make it simple and descriptive, which means an issue should include only one problem at a time and be specific on it. For example, in the title, "Aesthetics" and "stability" are very general words, so not everyone could understand what this issue is about by only looking at its title. It would be better if the title is directly related to the bugs/improvement you described in the comments. Also, you mentioned two problems in this issue, and they are all very good points. However, they are not strongly related. Most probably we will resolve them in separate branches and PRs, so it would be easier to track progress if they are separate issues.

I will leave it to you if you would like to fix it. Feel free to contact us if you have more questions. Thanks again for your contributions. 😸

**Comment by zhaosj975** [comment]
@wxharry  Sry for being so late to reply, and thanks for your advice and encouragement~I learned from them a lot ! And I will learn to fix it later~ ✨
