### ISSUE TITLE
[Bug] Why 17?

### ISSUE THREAD

**Issue by TieWay59** [hypertrons/hypertrons-crx#758]
### Version

latest

### Current Behavior

![image](https://github.com/hypertrons/hypertrons-crx/assets/40034603/89dd318c-d48a-4b29-b426-f8f3d934f0af)

### Expected Behavior

There should not be any extra number between neighboring months.

### Environment

```markdown
- OS: ubuntu
- Browser: chrome
```

### Any additional comments?

Or maybe I miss something? Let me know if it's by design.

**Comment by tyn1998** [comment]
Hello @TieWay59, could you provide the repo url?

**Comment by TieWay59** [comment]
@tyn1998 https://github.com/jmorganca/ollama

sorry I forgot it.

**Comment by TieWay59** [comment]
![image](https://github.com/hypertrons/hypertrons-crx/assets/40034603/269c3441-e526-4f2f-a1a1-707c0cad43aa)

https://github.com/biomejs/biome

@tyn1998 more example ↑

**Comment by wxharry** [comment]
It is because we didn't set the [minInterval for x-axis](https://echarts.apache.org/en/option.html#xAxis.minInterval). It fixes the bug if we set it to a month.
<img width="652" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/39271899/5670fa3f-51e4-4a9b-8929-2c0b463b76e2">
<img width="375" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/39271899/74af3ad0-e57d-4903-bfe1-7551a3801d32">
