### ISSUE TITLE
[Bug] activity.json only includes year data so the double bar chart shows only openrank bars

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#776]
### Current Behavior

Related repo: https://github.com/LlamaFamily/Llama-Chinese

<img width="1834" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/9506a1a6-4344-4999-a654-d291870d6bd6">

### Environment

```markdown
- OS:
- Browser:
```

**Comment by frank-zsy** [comment]
I will look into this and actually this should be a bug of OpenDigger but not HyperCRX

**Comment by HalloMelon** [comment]
Hello @frank-zsy ，is there any progress recently? 🌹

**Comment by frank-zsy** [comment]
@HalloMelon I can tell that it is caused by the name change of the repo, I can see the repo changed its name in 2023.12 and 2024.1 twice. So the monthly data went into the old name which is https://oss.x-lab.info/open_digger/github/LlamaFamily/Llama2-Chinese/activity.json , and the yearly data went into the current file. It is definitely an OpenDigger bug in the monthly export task, I am still working on it.

**Comment by tyn1998** [comment]
closed via https://github.com/X-lab2017/open-digger/pull/1541
