### ISSUE TITLE
[Bug] Wrong metric data used in contributors chart.

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#820]
### Version

1.9.6

### Current Behavior

As implemented in https://github.com/hypertrons/hypertrons-crx/pull/794 , the data used right now is `new_contributors`, but we should use `contributors` metrics because the meaning of the chart just like `participants`, which is the active contributors in the repo but not new contributors.

### Expected Behavior

Use `contributors` metrics instead of `new_contributors`

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

**Comment by frank-zsy** [comment]
Can use https://github.com/redis/redis to check the data, contributors count in the repo should 4 but not 0.

**Comment by tyn1998** [comment]
Hello @Tenth-crew, could you handle this?

**Comment by Tenth-crew** [comment]
OK, I've made the changes. Previously, new_contributors was used because the Metric in opendigger's Readme did not list contributors but only new_contributors and Inactive contributors. I mistakenly thought that there were only these two metrics for contributors. If there is a complete metric somewhere, can you give me a link to check it out? In addition, maybe the metrics supported in the opendigger Readme can be updated later.
![81ff2ad71ec2f30789e11871d9a3b5dd](https://github.com/hypertrons/hypertrons-crx/assets/68376741/4edb6ea4-87a2-4dff-8ada-dfda82b28cb5)
![image](https://github.com/hypertrons/hypertrons-crx/assets/68376741/672ef78d-e11d-424d-a3ed-21ce15848b60)

**Comment by frank-zsy** [comment]
@Tenth-crew Yes, this should be a missing metric in README since the metric is implemented recently. Will fix this soon.
