### ISSUE TITLE
[Bug] Deployment Failures on Chrome Web Store and Edge Add-on Store

### ISSUE THREAD

**Issue by HalloMelon** [hypertrons/hypertrons-crx#884]
### Description:
Here are the details while trying to deploy using. :

1. **Chrome Web Store Deployment Failure**:
   - The upload to the Chrome Web Store failed with an `uploadState` of `FAILURE` and an `itemError`. But it shows "pending review" status in Google Play Store.

2. **Edge Add-on Store Deployment Failure**:
   - When attempting to deploy to the Edge Add-on Store, received an `HTTPError: Response code 401 (Unauthorized)`. This suggests that there is an issue with the authentication process, I updated the key in the edge developer mode background, but I couldn't find where to configure it on GitHub.

### Steps to Reproduce:
1. Run `deploy` in Action.
2. Observe the deployment process and log output.

**Comment by wxharry** [comment]
We are getting a 401 from the stores https://github.com/hypertrons/hypertrons-crx/actions/runs/11208576214/job/31177336200#step:7:30. Can you double-check the tokens and all those secrets stuff? They haven't been updated for at least two years.

**Comment by frank-zsy** [comment]
We use script https://github.com/hypertrons/hypertrons-crx/blob/master/scripts/deploy.js to deploy the extension to Chrome and Edge store.

If someone has the secrets and tokens in the process, he can run the script locally to check what happens.

And also we should modify the script to show error message better.

- To show Chrome response message, instead of[ output the object directly](https://github.com/hypertrons/hypertrons-crx/blob/master/scripts/deploy.js#L35), we should use `JSON.stringify(uploadRes, null, 2);` which will also show the detail of the [`itemError`](https://github.com/hypertrons/hypertrons-crx/actions/runs/11208576214/job/31177336200#step:7:22).
- We also need to catch the exception and output the result for Edge deploy process, right now the exception throws and there are too much things in the log.

**Comment by tyn1998** [comment]
![image](https://github.com/user-attachments/assets/c913d916-482a-496a-95cc-dd37389609dd)

https://xlab2017.yuque.com/me1x4f/fg8ngy/nm5bxv

@frank-zsy @HalloMelon @wangyantong2000 Hey guys, you are granted permission to the yuque document containing secret tokens of the two web stores for further investigation :)

**Comment by wangyantong2000** [comment]
![image](https://github.com/user-attachments/assets/4ab3aaa7-326d-466e-a5ac-7e0a323dd52e)
<img width="380" alt="image" src="https://github.com/user-attachments/assets/05296dfb-2d24-48cb-a8ff-bfd0fb26c91d">


I tried it locally. It's just because Edge's SECRET has expired. There is no problem with Chrome, I have updated Edge's SECRET.

**Comment by wangyantong2000** [comment]
<img width="637" alt="image" src="https://github.com/user-attachments/assets/a1d34a82-71b0-42f7-8766-5aa90128eed9">

At present, the release and deploy operations in the action can be restored to normal.
