### ISSUE TITLE
[Bug] FastPR appears page crash when clicking the "Edit" icon

### ISSUE THREAD

**Issue by xiaoya-yaya** [hypertrons/hypertrons-crx#921]
### Version

version 1.9.14

### Current Behavior

When I click the "Edit" icon, it consistently crashes and fails to load the Hack.md(I presume?) editing page.

https://github.com/user-attachments/assets/4b0156dd-3200-4336-9ae3-96235c38c767

### Environment

```markdown
- OS: MacOS Sonoma (v14.2), M2
- Browser: Chrome 130.0.6723.117  (arm64)
```

**Comment by wangyantong2000** [comment]
https://open-digger.cn/blog/2024-11-6-openleaderboard-monthly-report. The page looks like this URL. But this problem did not occur with me. I don't know what happened either. Is this a random problem or a persistent issue

**Comment by frank-zsy** [comment]
@xiaoya-yaya Is there any error message in your console, or can you open https://stackedit.io/app# in your browser? Since the StackEdit already starts, I think then content of the file is correctly loaded.

**Comment by frank-zsy** [comment]
Actually I think StackEdit may not be the best option we got. Because StackEdit requires a web server to host the service, so we need to use https://stackedit.io/app# as our editor and open it in an iframe. This makes it really hard to customize the editor in many ways, like auto scrolling or customize renderer.

This is an alternative called https://www.npmjs.com/package/@uiw/react-md-editor , which is local npm package without any web server dependency. As the open source component makes it possible to customize the editor as we need. I think we can investigate whether we can use this one instead of StackEdit.

**Comment by xiaoya-yaya** [comment]
> https://open-digger.cn/blog/2024-11-6-openleaderboard-monthly-report. The page looks like this URL. 

Yes, this is the correct URL I was browsing, and it's a persistent issue from my side.

> Is there any error message in your console, or can you open https://stackedit.io/app# in your browser? Since the StackEdit already starts, I think the content of the file is correctly loaded.

Yes, I can successful open https://stackedit.io/app# in my browser. Here is what I got from the console and I don't see any error message occured:

https://github.com/user-attachments/assets/20bd6d92-a239-445e-a208-a0664f688253

**Comment by frank-zsy** [comment]
It is really weird, can you open docs page? Or how about other websites like https://kaiyuanshe.github.io/oss-book/Open-Source-Security-Risks.html

**Comment by xiaoya-yaya** [comment]
The issue was suddenly fixed on both Kaiyuanshe and OpenDigger's websites. They are now rendered normally though I still don't know what was fixed. I will close the issue for now until others report similar issues.
